### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by b264** [angular-actioncable/angular-actioncable#43]
I think Rails5 is stable enough to cut a 1.0.0 release.  Any thoughts on this?

**Comment by razorcd** [comment]
I would wait until Rails 5 final release unless there are any real reasons to need 1.0.0 now

**Comment by b264** [comment]
https://github.com/rails/rails/releases/tag/v5.0.0

**Comment by b264** [comment]
https://github.com/angular-actioncable/angular-actioncable/releases/tag/1.0.0
