### ISSUE TITLE
Error: Unknown provider: tProvider

### ISSUE THREAD

**Issue by b264** [angular-actioncable/angular-actioncable#51]
Hi,
Please use minsafe controller as below, otherwise it will raise error "Error: Unknown provider: tProvider" on production, and use same thing for remaining controller from this files-
```
ngActionCable.factory("ActionCableChannel",['$q', 'ActionCableController', 'ActionCableWebsocket',
'ActionCableConfig', 'ActionCableSocketWrangler', function ($q, ActionCableController,
ActionCableWebsocket, ActionCableConfig, ActionCableSocketWrangler){
------your code --------
}]);
```

from @sudarshandhokale via https://github.com/angular-actioncable/angular-actioncable/commit/4f9ea61be47431991de4d448a79e20da2a2ff9c1#commitcomment-18673751

**Comment by b264** [comment]
For some reason, I have not seen this error in production environments, but it's a great suggestion

**Comment by b264** [comment]
fixed in https://github.com/angular-actioncable/angular-actioncable/releases/tag/1.1.0

**Comment by sudarshandhokale** [comment]
That's great 👍
