### ISSUE TITLE
Readme Example Issue

### ISSUE THREAD

**Issue by websitescenes** [angular-actioncable/angular-actioncable#58]
Under 'A better way', the Javascript example fails linting. I believe the issue is with the line:

`var consumer = new ActionCableChannel("MyChannel", {user: 42, chat: 37}));`

It appears to have an extra ')' at the end. I'm happy to make a pull request if you believe that this is indeed an issue. Thanks.

**Comment by b264** [comment]
Yes; this does appear to be a typo.  PR is always welcome.  The same line here does not have the extra `)`: https://github.com/Neil-Ni/rails5-actioncable-angular-demo/blob/master/client/index.html#L50

**Comment by b264** [comment]
Closed by https://github.com/angular-actioncable/angular-actioncable/pull/59
