### ISSUE TITLE
change ActionCableConfig.wsUri

### ISSUE THREAD

**Issue by hiehuehue** [angular-actioncable/angular-actioncable#61]
if
`ActionCableConfig.autoStart = false;`
then before initiatiing actioncable with
`ActionCableSocketWrangler.start()`
user should have the option to alter ActionCableConfig.wsUri

**Comment by b264** [comment]
Thanks for reporting this.  It should be fixed shortly by https://github.com/angular-actioncable/angular-actioncable/pull/62/commits/a806d262d3640e7c0d6f0cf20bf5bde5038feeed

**Comment by hiehuehue** [comment]
thanks for the a fast fix

**Comment by b264** [comment]
published as https://github.com/angular-actioncable/angular-actioncable/releases/tag/1.1.1
