### ISSUE TITLE
$q.resolve() Error during subscription

### ISSUE THREAD

**Issue by NanaPhil** [angular-actioncable/angular-actioncable#68]
angular.js:11706 TypeError: $q.resolve is not a function    after the subscription method is called

**Comment by b264** [comment]
Do you have a sample of the code that's throwing the exception?

**Comment by NanaPhil** [comment]
Fixed the issue but i get that error after i refresh the controller , the code breaks

**Comment by b264** [comment]
Without code samples, it's hard to assist, but I would check to ensure that you are passing functions to the subscribe method and that you aren't using any third-party promise librarises, but just the promise that ships with Angular 1.x

**Comment by NanaPhil** [comment]
yeah i am using the demo code from the Read me

**Comment by b264** [comment]
Try starting with the demo mentioned at https://github.com/Neil-Ni/rails5-actioncable-angular-demo  Does that work

**Comment by NanaPhil** [comment]
it works  but when i injected into my project it still works but after i refresh the app then i get the error

**Comment by b264** [comment]
What version of Angular do you have

**Comment by NanaPhil** [comment]
I have seen the problem . When i refresh in a different state and comes back to the socket controller it works  fine. So what can be the cause of that break? Angular 1.4X

**Comment by b264** [comment]
Whatever is causing the log message for `XHR finished loading: GET` try disabling that and see what happens. Is that attempting to access the same URL as the Websocket connection?
