### ISSUE TITLE
Watchers on ActionCableSocketWrangler connections are not picking up the changes

### ISSUE THREAD

**Issue by b264** [angular-actioncable/angular-actioncable#7]
Changes on any of the ActionCableSocketWrangler connection functions:
```
ActionCableSocketWrangler.connected()
ActionCableSocketWrangler.connecting()
ActionCableSocketWrangler.disconnected()
```
are not triggering the watchers (not updating in UI)

**Comment by b264** [comment]
We can control when the digest loop runs to alleviate this as well

**Comment by razorcd** [comment]
yes, I agree
`$scope.wrangler= ActionCableSocketWrangler` in controller
and
```
{{wrangler.disconnected}}
{{wrangler.connecting}}
{{wrangler.connected}}
``` 
in views
