### ISSUE TITLE
Cannot access component data when removing the `.then(...)` from the example

### ISSUE THREAD

**Issue by zedtux** [angular-actioncable/angular-actioncable#76]
I have an AngularJS 1.x and a Rails 4.2 application which uses ActionCable in order to push updates from the back to the front, and this package solved my issue to access the component data from the ActionCable call.

I have used the [A better way](https://github.com/angular-actioncable/angular-actioncable#a-better-way) from the `README.md` file, which works just fine, and then I was looking at the `.then(...)` part.
As I'm not using ActionCable to push messages, I removed the `.then(...)` part and my code started to fail to update view as it couldn't access my component data.
Putting back the `.then(...)` fixes the issue 😨.

Here is how looks like my code:

```javascript
function SharedMsStockResponse($q, $scope, x2js, stockResponseService, Supplier, CHANNELS, ActionCableChannel) {
  var ctrl = this
  ...
  // ActionCable receiving the backend response from the Stock Response request
  // See stockResponseService
  var consumer = new ActionCableChannel(CHANNELS.EXTERNAL_URL_CALLS, {});
  var callback = function(result) {
    var stockResponseRow = null
    if (result.data && result.data.supplier_id && ctrl.saleRow.stockResponses) {
      for (i = 0; ctrl.saleRow.stockResponses.length; i++) {
        ...
      }
    }
  }
  consumer.subscribe(callback).then(function() {
    $scope.sendToMyChannel = function(message) { consumer.send(message, 'send_a_message'); };
    $scope.$on("$destroy", function() {
      consumer.unsubscribe().then(function() { $scope.sendToMyChannel = undefined; })
    })
  })
}

angular.module('MY_APP')

.component('sharedMsStockResponse', {
  templateUrl: ...,
  controller: ['$q', '$scope', 'x2js', 'stockResponseService', 'Supplier', 'CHANNELS', 'ActionCableChannel', SharedMsStockResponse],
  bindings: {
    ...
    saleRow: '<'
  }
})

```

The error is thrown from the line where I'm trying to get `ctrl.saleRow.stockResponses.length`.
FYI anywhere else, in my component, the `ctrl.saleRow` has a value.

Is there anything I'm doing wrong or misunderstood? Or do you think there could be a bug in the package?

**Comment by b264** [comment]
try it with `.then(function() {})`

**Comment by zedtux** [comment]
No, it's still failing with:

`Uncaught TypeError: Cannot read property 'stockResponses' of undefined` on the line:

```javascript
if (result.data && result.data.supplier_id && ctrl.saleRow.stockResponses) {
```

**Comment by b264** [comment]
Somehow `ctrl.saleRow` is not being defined [yet] when the callback runs, I'm not sure that's in the library's code

**Comment by zedtux** [comment]
Finally I figured out what was wrong.

The minimal code I had to keep, in order to get my code working is the following:

```javascript
```

In my application, I'm using angular-actioncable in a component and the component was built, destroyed and re-built again, so the `ActionCableChannel` object was referring an instance of the component that no more exists.

**Comment by b264** [comment]
If you can add any relevant tidbit to the readme to save someone else some time, please feel free to submit a PR.... or maybe a troubleshooting readme...

Also I suspect that you still had an open susbscription in Rails without the .unsubscribe as well which after time would be an issue.  Kind-of like a memory leak but a little different
