### ISSUE TITLE
access existing subscription 

### ISSUE THREAD

**Issue by rickybrown** [angular-actioncable/angular-actioncable#78]
Here's the scenario:

1: subscribe to channel in controller
```
consumer = new ActionCableChannel("ChatChannel", object);
consumer.subscribe(callback).then ...
```

2: change state (without unsubscribing)
3: change back to previous state
4: reassign `consumer` variable to existing `ActionCableChannel("ChatChannel", object)`, without creating duplicate subscription.

Does this make any sense? should i not need to do this?

**Comment by b264** [comment]
Step 4 should be unnecessary, yes.  If it's not working do you have a way to recreate the problem using minimal code?

**Comment by rickybrown** [comment]
I can see it would be unnecessary, but here's a better explanation: This happens in the "thread" controller. if i am scrolling through contacts and i tap on one to open a thread, the 'thread' controller should check if a subscription with this contact already exists before creating a new one. 

```
if(subscription-doesnt-exist-yet){
  consumer = new ActionCableChannel("ChatChannel", {sender: 'me', recipient: 'someone'});
} else {
  consumer = ActionCableChannel("ChatChannel", {sender: 'me', recipient: 'someone'});
}

consumer.subscribe
```

Does this make sense? because i need to switch between threads/subscriptions, and i dont want to create a new ActionCableChannel everytime (unless its a new thread), because duplicate messages would push through in that case

**Comment by rickybrown** [comment]
Nevermind, i know what i need to do. Thanks :)
